[package]
name = "luanti-mts"
description = "Read and write Luanti (formerly Minetest) schematic files (MTS)"
version = "0.1.0"
edition = "2024"

[dependencies]
flate2 = "1.1.2"
rstest = "0.25"
thiserror = "2.0.12"
winnow = "0.7.12"
